### ISSUE TITLE
Add Form component

### ISSUE THREAD

**Issue by xaviervia** [klarna/ui#106]
Proposed API (compatible with the current `uncontrolled` HoC):

```javascript
<Form
  fields={{
    account: {
      label: 'Account',
      position: 0
    }
  }}

  // And validate that all values match to a field, otherwise
  // throw error of some kind
  defaultValues={{
    account: '123',
    password: ...
  }}

  values={{
    account: '123',
    password: ...
  }}

  // Bundle and throttle the individual calls from each Field, for autofill
  onChange={({account: '1234', password: ...}) => }
/>
```

Ping @JoakimLofgren

**Comment by Nevon** [comment]
What is the intended purpose of this component?

**Comment by xaviervia** [comment]
Provide a single-entrypoint interface for creating condensed forms, eventually with auto calculated layout. Much like the CAF. 

In first drop though I will not provide any calculation for the layout, that can be added later since it will not be a breaking change.

Wdyt?

**Comment by Nevon** [comment]
What kind of responsibilities would it have? I could see the auto layouting, but then that would probably belong in a `fieldset` style component instead.

**Comment by xaviervia** [comment]
Continues in #111 . @Nevon, @joaomilho posted more or less the same concerns there, please join in there if you are interested =) tl;dr though I think it will be `Fieldset` instead, it's not a Form.
