### ISSUE TITLE
Checkbox multi-line label looks misaligned

### ISSUE THREAD

**Issue by Nevon** [klarna/ui#112]
<img width="341" alt="screen shot 2016-10-13 at 15 30 06" src="https://cloud.githubusercontent.com/assets/83586/19350932/fea81016-9159-11e6-84f6-77186d4db4a4.png">

To me it looks like the text is too far down.

**Comment by xaviervia** [comment]
Eagle-eye @Deschtex is out so let's ping @zenona and @hannah-ahl instead :D

**Comment by Nevon** [comment]
The legal variant is even worse.

<img width="338" alt="screen shot 2016-10-13 at 16 36 53" src="https://cloud.githubusercontent.com/assets/83586/19353333/4caa6b7a-9163-11e6-9ba3-028219d27ad5.png">

**Comment by hannah-ahl** [comment]
Body text should be pushed up 1px
Legal text should be pushed up 1px if we want to stay on the grid, and 2px if we want to have it visually centered.

Regards, team pixel vision
Hannah Ahl
Product Designer
Product
+46 700 029 449 <tel:+46+700+029+449>
Klarna AB
Sveavägen 46, 111 34 Stockholm
Tel: +46 8 120 120 00 <tel:+46812012000>
Reg no: 556737-0431
klarna.co <http://klarna.com/>m
