### ISSUE TITLE
Add Date of Birth field

### ISSUE THREAD

**Issue by xaviervia** [klarna/ui#127]
Yes. It's happening.

**Comment by jonotrujillo** [comment]
Is it going to be a date component or a masked component?

**Comment by cskeppstedt** [comment]
A day to remember

**Comment by xaviervia** [comment]
@jonotrujillo it's going to be more or less a copy paste of your implementation.

**Comment by Nevon** [comment]
Well, this project was good while it lasted. Nice to have known you, Fernando!
