### ISSUE TITLE
Debounce resize in Collapsible component

### ISSUE THREAD

**Issue by xaviervia** [klarna/ui#152]
@Nevon said in https://github.com/klarna/ui/pull/150#discussion-diff-85144217R22

> This is going to cause the `render` method to get called on every resize event, which you might have happen more than once per actual browser rendering. Since `getBoundingClientRect` causes a layout, this is very expensive. Check #144 to see how I debounced the event so it only happens when the browser will actually render a new frame. It made a world of difference in some browsers.

Let's fix this.

**Comment by Nevon** [comment]
Fixed by 9150357eb5e3387b8b9905c3e89064239de1afc8

**Comment by xaviervia** [comment]
Oh well. Snabba Brunn.
