### ISSUE TITLE
Too big value in input field change row on smaller screens 

### ISSUE THREAD

**Issue by PatrikE** [klarna/ui#172]
### Environment
* all devices and browsers.

### Issue
* when user choose a value of his choice then value can drop to another row if value is too big
 
![screen shot 2016-11-07 at 10 57 02](https://cloud.githubusercontent.com/assets/3233303/20053648/d8bd4ffe-a4d9-11e6-9f0c-08cadb4c9bb0.png)

**Comment by xaviervia** [comment]
Will be worked on in the PR
