### ISSUE TITLE
Footprint

### ISSUE THREAD

**Issue by joaomilho** [klarna/ui#181]
Following @ctaintor 's priorities, I feel we could find a way to estimate and present both component's and the whole lib size in the showcase, and/or as a test, and/or as a build step. The goal is mainly to create awareness and make us focus on leaner solutions.

**Comment by JoakimLofgren** [comment]
We could create a little graph over all the versions to see how the size varies.

**Comment by Nevon** [comment]
I recently learned about a package called `source-map-explorer`, which is the best bundle analyser I've seen so far.

I ran it against a build of the latest master. You can see the interactive results here: https://rawgit.com/Nevon/22c1f6a5b0aa5bf7c8350248c00318e3/raw/ec408f51a1c7834201eb646ef15680d14ea25162/klarna-ui-bundle-analyze.html

Not terribly useful on a day to day basis, but it could be useful to explain sudden increases in bundle size, to see that you're not bundling something twice or including a dependency that's much larger than you'd have thought.

**Comment by xaviervia** [comment]
Well @Nevon 's solution is in master now! I'm closing this one :)
