### ISSUE TITLE
Wrapper needs keyboard interaction

### ISSUE THREAD

**Issue by xaviervia** [klarna/ui#20]

**Comment by Nevon** [comment]
What does this mean? You mean tabindexes for the close icon etc? Something I'm missing is to be able to close it by pressing escape, but since it's a fully uncontrolled component, I'm not sure how we would model that - or if it should be left up to the applications to implement themselves.

**Comment by xaviervia** [comment]
Both.

This as a placeholder issue, we can outline the requirements in more detail. What comes to mind is:

- Close and Back icons in tabindex
- Esc key to close the dialog
- Clicking in the overlay closes the dialog

In a way, actually closing the dialog would be (for now) left to the applications.... although I guess we could make this a pseudo controlled component with the uncontrolled decorator. what we need to add is the ability to _capture_ the esc key and clicks in the overlay and all that.

**Comment by xaviervia** [comment]
I wonder how could this even be done. For key board interactions to be captured in the context of the Dialog, the events have to listened to in the `window` or some element within the Dialog needs to be in focus. Either way, and in the absence of some hack, it doesn’t feel that the Dialog itself can capture these events. Maybe this is something that unfortunately consumers will have to do on their own listening to `window.addEventListener('keydown')` and using the information to close the Dialog when it’s open.

**Comment by Nevon** [comment]
Why couldn't the dialog listen on the window?

**Comment by xaviervia** [comment]
Isn't that rather weird? Separation of concerns and all that.

**Comment by Nevon** [comment]
I don't think you mean separation of concerns, but I think I understand what you mean. It's listening in on global events, but I think it's okay. If you press escape when a modal is open, we want to close it regardless of where your focus was at the time.

**Comment by xaviervia** [comment]
I like this line of reasoning. I guess an escape key pressed on while the input is on a field could be intercepted by the the field with stopPropagation so that the window doesn't capture it and the Dialog is closed.

**Comment by xaviervia** [comment]
BTW this is a feature of the `Wrapper`, not the "Dialog". For starters, the Dialog does not (and never did) provide an `onClose` handler, while the Wrapper does. Also the Dialog itself is just a layer inside the full screen context, which lives alongside the Backdrop and potentially other layers. I'll rename the ticket.

And in this case, what you say makes even more sense. The only annoyance we will have is that pressing "escape" when the template demos are open will fire the `onClose` function of all of them.

While we are at it, should we provide a key shortcut for the dialog "back" button? It feel that that should be probably tied to the browser navigation.

**Comment by xaviervia** [comment]
Will be done in https://github.com/klarna/ui/pull/94
