### ISSUE TITLE
Stop hand icon

### ISSUE THREAD

**Issue by hogis** [klarna/ui#242]
The stop hand icon is requested to be present in the toolkit.

example: 
![stop hand](https://d30y9cdsu7xlg0.cloudfront.net/png/11642-200.png)

**Comment by Nevon** [comment]
What meaning does this have semantically? There are icons for Error, Warning and Cancel.

Same goes for #243.

**Comment by hogis** [comment]
Well, for us it does in the merchant portal for some orders states. We use these icons today and we draw them from our own toolkit. Since we want to migrate fully to klarna-ui toolkit we would like to have these available. They are more of hints to the user than a reaction like Error, Warning and Cancel.
