### ISSUE TITLE
Keyboard navigation of Radio selector is broken in IE (at least 9 and 10)

### ISSUE THREAD

**Issue by xaviervia** [klarna/ui#261]
It’s a weird issue. We need to investigate further but it seems to be related with controlled focus and/or controlled value.

The simplest way to reproduce is to open https://klarna.github.io/ui/#Radio in IE 9 or IE 10, select an option in any Radio selector and try to change the selection with the keyboard arrows. There are several related issues though: try selecting an element and reloading and then pressing the space bar or the arrows.

 Not tested in other IE versions but it might reproduce in them.

**Comment by dmitriid** [comment]
Doesn't work on Safari 10.0.3 either :(

Same for Switches

**Comment by xaviervia** [comment]
As far as I know Safari does not support keyboard navigation for `<input>` elements that are not of of type `text`. You can try this yourself in https://codepen.io/anon/pen/LWXJWW

**Comment by dmitriid** [comment]
It does if enabled in System -> Preferences -> Keyboard -> Shortcuts -> Full keyboard access -> All controls :)

For comparison see spectre.css's implementation (which handles keyboard input): https://picturepan2.github.io/spectre/elements.html#forms
