### ISSUE TITLE
Peer dependencies

### ISSUE THREAD

**Issue by Nevon** [klarna/ui#309]
How come we are listing react, react-motion and ramda as peer dependencies? The purpose of peer dependencies is to say that you depend on a package even though you never actually `require` it. The canonical use-case is for plugins, so that if you for example build a webpack plugin, you would list webpack as a peer dependency to be able to express that you are compatible with a certain version of webpack, even though you never `require` webpack in your code.

The UI components certainly `require` all of react, react-motion and ramda, so they should be listed as dependencies (which they already are, which makes me even more confused about why they are also listed as peer dependencies).

**Comment by xaviervia** [comment]
Hm. The reason we have this is to hack our way into making sure React, React Motion and Ramda are not bundled more than once by the consumer products, since they will include React through the UI and directly. If there is a better way of doing it, we should totally go for that.

**Comment by Nevon** [comment]
They're already listed as direct dependencies though, so I don't see why listing them as peerDependencies as well would make any difference.

**Comment by xaviervia** [comment]
No, not exactly. They are listed as `devDependencies`, not regular ones.

**Comment by Nevon** [comment]
Oh right, my mistake. Well, using peerDependencies this way isn't exactly _correct_. It's essentially being used now as a way of telling the consumers that they should have these dependencies available, but from a technical perspective you might as well not include those dependencies at all.

So, since this is essentially the same as a section in a readme, I suppose it's as good as any other way.
