### ISSUE TITLE
Fields in the Fieldset component are given IDs that starts with "undefined__"

### ISSUE THREAD

**Issue by kgilles** [klarna/ui#367]
The elements `div`, `label`, `input` and `select` (maybe some more) that are related to a Field component within a Fieldset are given an ID that starts with `undefined__` if no ID is set when defining the Fieldset component.

Inspect the elements on this page to see how it looks: https://klarna.github.io/ui/#Fieldset

**Comment by xaviervia** [comment]
Let's continue in the PR
