### ISSUE TITLE
Cannot submit by hitting enter in SingleInputPrompt

### ISSUE THREAD

**Issue by OscarF** [klarna/ui#372]
I have a SingleInputPrompt with a PNO field and an accept button. Hitting enter in the field does not take me further in the flow.

Steps to reproduce:
1. Render a SingleInputPrompt with a field and an onAccept
2. Enter something in the input field
3. While still in the input field hit enter on your keyboard
4. Nothing happens.
Expected behavior: Goes to next screen

Example code
```javascript
export default function EnterPNO ({getUserState, setUserState, stepNext, goTo}) {
  return (
    <DialogFrame onClose={() => goTo(2)}>
      <SingleInputPrompt
        title='Personnummer'
        summary='Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt'
        label='Personnummer'
        accept='Fortsätt'
        brandVolume='high'
        illustration={<PNOLady />}
        onAccept={stepNext}
        onChange={(e) => setUserState('pno', e.target.value)}
        className={styles.pnoInput}
        type='tel'
        giant
      />
    </DialogFrame>
  )
}
```

**Comment by abdulhannanali** [comment]
@OscarF Is this still up for grabs would like to work on it?
