### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by marcusnielsen** [klarna/ui#407]
I just found this repo, and felt like I needed to just reach out as a dev to say thank you, Klarna!

Not many big companies in Sweden has started open sourcing their stuff yet, and this gives me something to share with my team members over at linasmatkasse.

So thank you for making other people's jobs easier and caring about open source <3

(Just read, feel good, and close the issue.)

**Comment by Nevon** [comment]
Thank you right back from all of us at Klarna!

![High five](https://media.giphy.com/media/1HPzxMBCTvjMs/giphy.gif)
