### ISSUE TITLE
Consider using Greenkeeper

### ISSUE THREAD

**Issue by xaviervia** [klarna/ui#51]
https://greenkeeper.io/

**Comment by joaomilho** [comment]
Can you briefly explain greenkeeper? The website is fuzzy

**Comment by xaviervia** [comment]
It essentially creates PRs when a dependency can be safely updated, so the only thing remaining to do is to merge. The idea is to try to keep up to date without manually testing each dependency to see if it's possible to update it.

But I'm not 100% about this yet, I'd say we can wait until we are happy with it in [Sagui](https://github.com/saguijs/sagui)

**Comment by xaviervia** [comment]
Greenkeeper seems to be a little _green_ (pun intended). It was a pain in Sagui and didn't add much value. I'm rejecting this for now.
