### ISSUE TITLE
Stability and explicit support periods

### ISSUE THREAD

**Issue by Nevon** [klarna/ui#60]
This is obviously a bigger issue of allocating manpower, but I think it's good to start having a discussion regarding stability and consumer experience.

Within Klarna projects, we have already experienced quite a bit of churn regarding the ui components. Within one project that shall remain unnamed, we are currently using a combination of the _old_ closed-source ui toolkit and the first iteration of the open-source `ui-react-components` project. Another project has `ui-react-components` as well as the new `ui` components, and that project isn't even 6 months old.

It's natural that there is some churn while the project is getting started, but at some point there has to be a commitment to stability. If the stated goal of the project is to promote consistency across products, and reduce the amount of duplicated work between teams, then the consuming teams will need to be able to commit to a version of the toolkit and know that it will be alive and supported for at least some time, without each team needing to go through a painful migration process multiple times per year.

**Comment by xaviervia** [comment]
Correct. That is the stated purpose of dedicating full time resources to this project. But about stability in general I can give some updates:

- The upcoming version 1.0.0 (we are in the RC 11 and closing in) contains a file structure and API concepts that we are pretty happy with and already proved to be able to support a significant amount of use cases. There is no plan to change the main APIs (such as how elements are consumed or the CSS classes are named) after that, except only to significantly simplify them in an almost background compatible way (see https://github.com/klarna/ui/issues/45).
- The expected evolution of the components is to be around building already built _compositions_, or "molecule" and "organism" level components according to atomic design nomenclature, not changing the atom level ones. The current building blocks are seen as pretty solid and there is no expectation of the current components to change much (aside from re stylings that should not affect APIs). We expect to add more and more atomic components in the future, but not to change any of the current ones.

The idea also is to be more transparent about upcoming changes in the future, maybe composing regular newsletters, adding guides and maintaining a blog about the principles that guide the decisions taken in the library, but that of course will take some more resources and we haven't come up with a strategy yet.

If all of this doesn't hold and a big migration is needed (which could be the case if we were to face a full redesign of the brand) the expectation is that we would have a very specific migration guideline to cater for it. But again, this is not expected nor desired.

**Comment by xaviervia** [comment]
Since now there are proper release notes and the project follows Semver I'll close this one. I'll try to also share plans for the future in advance when big changes are upcoming.
